### ISSUE TITLE
Argument is not assignable to parameter

### ISSUE THREAD

**Issue by rutech-rmi** [FirebaseExtended/codelab-kanban-fire#18]
Hello, 
When practicing according to the tutorial (https://developers.google.com/codelabs/building-a-web-app-with-angular-and-firebase#4) I get following ERROR:
_Argument of type 'CdkDragDrop<Task[], any, any>' is not assignable to parameter of type 'CdkDragDrop<Task[] | null, Task[] | null, any>'_

It's working when I remove the part `|null` from `drop(event: CdkDragDrop<Task[]>): void` in file src/app/app.component.html

**Comment by MarleySetwaba** [comment]
Also Try Adding $any To All The (cdkDropListDropped) = "drop($event)" In All The Swimlanes In Your app.component.html File.

I.E.
(cdkDropListDropped) = "drop($any($event))"
Dont Know Why But It Worked For Me.

**Comment by rostag** [comment]
Possible solution is in this issue: #23
