### ISSUE TITLE
Is entryComponents line missing here?

### ISSUE THREAD

**Issue by ishandesilva2** [FirebaseExtended/codelab-kanban-fire#3]
https://github.com/FirebaseExtended/codelab-kanban-fire/blob/eef0dc203b0b6f322aee1f081a0d86cf27285889/src/app/app.module.ts#L34

Kept getting the error `No component factory found for TaskDialogComponent. Did you add it to @NgModule.entryComponents?` Worked after adding the line `entryComponents: [TaskDialogComponent]` in `app.moudle.ts`.

Please check.

**Comment by mgechev** [comment]
Entry components are not necessary after v9 with Ivy enabled.
