### ISSUE TITLE
Hitting cancel when entering new task results in empty task/error

### ISSUE THREAD

**Issue by aeleneski** [FirebaseExtended/codelab-kanban-fire#4]
In Step 6 (before integrating Firebase), you can hit New Task, then before filling out the form hit the Cancel button.

This will still add a blank task to the Backlog card since we are just subscribed to the after close event.

```
    dialogRef
      .afterClosed()
      .subscribe((result: TaskDialogResult) => this.store.collection('todo').add(result.task));
```

When doing the same steps after integrating Firebase in Step 11 you will now see an error in the console similar to

![image](https://user-images.githubusercontent.com/6454039/101285848-7c5cd900-37b5-11eb-9b2c-c9b89646ec74.png)

**Comment by eidsvold** [comment]
Same issue.

**Comment by mgechev** [comment]
This should be fixed now :)
