### ISSUE TITLE
issue with Types mismatching

### ISSUE THREAD

**Issue by mjs001** [FirebaseExtended/codelab-kanban-fire#5]
having the following issue:

![Capture](https://user-images.githubusercontent.com/50973969/104158081-34cbfd00-53b2-11eb-9dc5-8df65b882114.PNG)

I have double checked all of the code including copy and pasting his code over mine. Still having this issue.

**Comment by 49e94b8f256530dc0d41f740dfe8a4c1** [comment]
@mjs001 are you on `Angular 11` or `Angular 10`?

**Comment by mjs001** [comment]
I am on angular 11

**Comment by mgechev** [comment]
The example is using v10 without strict template type checking enabled. As a quick hack, you can do a typecast to `any`. Updating the sample project here will not be feasible because it'll get out of sync with the video.

**Comment by mjs001** [comment]
Thank you, I will try this and let you know!

**Comment by bthayer-insight** [comment]
Setting "strictTemplates" to false in tsconfig.json fixed this for me using Angular 11

`"angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": false
  }`

**Comment by mgechev** [comment]
This should be fixed now :)
