### ISSUE TITLE
problem when dragging and dropping after modifying the code to firebase

### ISSUE THREAD

**Issue by DAmrGharieb** [FirebaseExtended/codelab-kanban-fire#7]
hi  team
I suffered a problem implementing the code everything was ok until I changed like what you did when making the app communicate to firebase instead of in-memory array I think the flaw that the data now when returned from the event is observable not array so can you change the code this is my trial but now no error but no drag-drop

`
drop(event): void {
    if (event.previousContainer === event.container) {
      return;
    }
    if (!event.previousContainer.data || !event.container.data) {
      return;
    }
    let item = null;

    event.previousContainer.data.subscribe(
      (res) => (item = res[event.previousIndex]),
      (err)=>{},
      ()=>{
        this.store.firestore.runTransaction(() => {
          const promise = Promise.all([
            this.store.collection(event.previousContainer.id).doc(item.id).delete(),
            this.store.collection(event.container.id).add(item),
          ]);
          return promise;
        });
        transferArrayItem(
          event.previousContainer.data,
          event.container.data,
          event.previousIndex,
          event.currentIndex
        );
      }
    );

   
  }
`

**Comment by DAmrGharieb** [comment]
![image](https://user-images.githubusercontent.com/69108600/114959059-92199380-9e64-11eb-82c3-82a775b1c863.png)
this is the error before modifying the code

**Comment by DAmrGharieb** [comment]
i made some modification i hope to be the best practise

`
`
    drop(event: CdkDragDrop<Observable<Task[]>| Task[]|null |any>): void {
      if (event.previousContainer === event.container) {
        return;
      }
      if (!event.previousContainer.data || !event.container.data) {
        return;
      }

    const item = event.previousContainer.data._value[event.previousIndex];
  
    this.store.firestore.runTransaction(() => {
      const promise = Promise.all([
        this.store.collection(event.previousContainer.id).doc(item.id).delete(),
        this.store.collection(event.container.id).add(item),
      ]);
      return promise;
    });

    transferArrayItem(
      event.previousContainer.data._value,
      event.container.data._value,
      event.previousIndex,
      event.currentIndex
    );

   
  }`
`

**Comment by nistrar** [comment]
I changed

 const item = event.previousContainer.data._value[event.previousIndex];

to 
 
 const item = event.previousContainer.data.[event.previousIndex];

and it works for me

**Comment by DAmrGharieb** [comment]
when switching to firebase the returned data is observable of tasks not array of task so data property is observable, not plain array

**Comment by nistrar** [comment]
I had problems with index when dropping and using data._value

**Comment by mgechev** [comment]
@nistrar's comment seems to resolve the issue.
